### PR TITLE
bug-fix illegal arg ex for enum.

### PR DESCRIPTION
**Pull request by morozvitali**
Bug Fixes in the project to ensure the avoidance of Exception when using enams (Exceptions).
* Added a condition when the city is unknown.

### CODE REVIEW

**Review by oleksandr-sydorskyi — APPROVED** [review]
The changes you've implemented in the project were very beneficial:
- Handling the error is a great solution. Now, if a user enters a location not in the enum, it won’t cause the program to crash.
- However, displaying "UNKNOWN" for the location might confuse users. They know the location but might have made a typo. Perhaps suggesting them to re-enter the location would be more user-friendly. But this could be a matter of preference.

**Review by KaterynaMir — APPROVED** [review]
The code looks fine and can be merged to the main.

However, the last task was to refactor code and use one and the same approach to treat the IllegalArgumentException in enums:
"Для кращого засвоєння вивченого матеріалу, пропонується самостійно проаналізувати розглянуті підходи до уникнення IllegalArgumentException при використанні методу valueOf(...) з неіснуючим заченням енаму та здійснити код-рефактор для використання одинаково підходу у межах одного проєкту."

So you van chose one of the approaches (try-catch or fromString) and refactor code according to it.

**Comment by morozvitali** [comment]
Enum Location: Added a static fromString method that checks if the entered value exists among the enum constants. If a matching value is found, it is returned as an enumeration; if not, null is returned.

ClientService: Changed the buildClient method to use the new Location.fromString method to get the location of the value entered by the client. This allows unknown locations to be handled correctly, instructing the user to re-enter the location.

**Review by KaterynaMir — APPROVED** [review]
Good work! The code can be merged to the main.

**Review by oleksandr-sydorskyi — APPROVED** [review]

**Pull request closed without merging**
